# Generated by Django 3.1.3 on 2020-12-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagenames',
            options={'verbose_name_plural': 'About Page Names'},
        ),
    ]
