# Generated by Django 3.1.5 on 2021-05-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0002_auto_20210520_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='green_manure_destroyed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='green_manure_destroyed_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='green_manure_destroyed_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='manure_added',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='manure_added_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='manure_added_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
