# Generated by Django 3.1.5 on 2021-01-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0002_auto_20201218_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagenames',
            name='new_plan',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagenames',
            name='new_plan_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='new_plan_pl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
