# Generated by Django 3.1.5 on 2021-02-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0003_auto_20210118_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotatorEditorPageNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_plan', models.CharField(max_length=200)),
                ('new_plan_pl', models.CharField(max_length=200, null=True)),
                ('new_plan_en', models.CharField(max_length=200, null=True)),
                ('new_step', models.CharField(max_length=200)),
                ('new_step_pl', models.CharField(max_length=200, null=True)),
                ('new_step_en', models.CharField(max_length=200, null=True)),
                ('name_plan', models.CharField(max_length=200)),
                ('name_plan_pl', models.CharField(max_length=200, null=True)),
                ('name_plan_en', models.CharField(max_length=200, null=True)),
                ('name_step', models.CharField(max_length=200)),
                ('name_step_pl', models.CharField(max_length=200, null=True)),
                ('name_step_en', models.CharField(max_length=200, null=True)),
                ('plan_remove', models.CharField(max_length=200)),
                ('plan_remove_pl', models.CharField(max_length=200, null=True)),
                ('plan_remove_en', models.CharField(max_length=200, null=True)),
                ('step_remove', models.CharField(max_length=200)),
                ('step_remove_pl', models.CharField(max_length=200, null=True)),
                ('step_remove_en', models.CharField(max_length=200, null=True)),
                ('editme', models.CharField(max_length=200)),
                ('editme_pl', models.CharField(max_length=200, null=True)),
                ('editme_en', models.CharField(max_length=200, null=True)),
                ('switch_places', models.CharField(max_length=200)),
                ('switch_places_pl', models.CharField(max_length=200, null=True)),
                ('switch_places_en', models.CharField(max_length=200, null=True)),
                ('switch_with', models.CharField(max_length=200)),
                ('switch_with_pl', models.CharField(max_length=200, null=True)),
                ('switch_with_en', models.CharField(max_length=200, null=True)),
                ('switch_text', models.CharField(max_length=200)),
                ('switch_text_pl', models.CharField(max_length=200, null=True)),
                ('switch_text_en', models.CharField(max_length=200, null=True)),
                ('u_edit_step_no', models.CharField(max_length=200)),
                ('u_edit_step_no_pl', models.CharField(max_length=200, null=True)),
                ('u_edit_step_no_en', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('title_pl', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('descr', models.CharField(max_length=200)),
                ('descr_pl', models.CharField(max_length=200, null=True)),
                ('descr_en', models.CharField(max_length=200, null=True)),
                ('early_crop', models.CharField(max_length=200)),
                ('early_crop_pl', models.CharField(max_length=200, null=True)),
                ('early_crop_en', models.CharField(max_length=200, null=True)),
                ('late_crop', models.CharField(max_length=200)),
                ('late_crop_pl', models.CharField(max_length=200, null=True)),
                ('late_crop_en', models.CharField(max_length=200, null=True)),
                ('destroy_early_crop', models.CharField(max_length=200)),
                ('destroy_early_crop_pl', models.CharField(max_length=200, null=True)),
                ('destroy_early_crop_en', models.CharField(max_length=200, null=True)),
                ('destroy_late_crop', models.CharField(max_length=200)),
                ('destroy_late_crop_pl', models.CharField(max_length=200, null=True)),
                ('destroy_late_crop_en', models.CharField(max_length=200, null=True)),
                ('add_fertilizer', models.CharField(max_length=200)),
                ('add_fertilizer_pl', models.CharField(max_length=200, null=True)),
                ('add_fertilizer_en', models.CharField(max_length=200, null=True)),
                ('add_fertilizer_onhover', models.CharField(max_length=800)),
                ('add_fertilizer_onhover_pl', models.CharField(max_length=800, null=True)),
                ('add_fertilizer_onhover_en', models.CharField(max_length=800, null=True)),
                ('change', models.CharField(max_length=200)),
                ('change_pl', models.CharField(max_length=200, null=True)),
                ('change_en', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Rotator Editor Page Names',
            },
        ),
        migrations.RemoveField(
            model_name='pagenames',
            name='editme',
        ),
        migrations.RemoveField(
            model_name='pagenames',
            name='editme_en',
        ),
        migrations.RemoveField(
            model_name='pagenames',
            name='editme_pl',
        ),
        migrations.RemoveField(
            model_name='pagenames',
            name='new_plan',
        ),
        migrations.RemoveField(
            model_name='pagenames',
            name='new_plan_en',
        ),
        migrations.RemoveField(
            model_name='pagenames',
            name='new_plan_pl',
        ),
        migrations.AddField(
            model_name='pagenames',
            name='all_plants',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='all_plants_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='all_plants_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regnames',
            name='refresh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='regnames',
            name='refresh_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='regnames',
            name='refresh_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regnames',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regnames',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regnames',
            name='name_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regnames',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regnames',
            name='password_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regnames',
            name='password_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regnames',
            name='re_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regnames',
            name='re_password_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='regnames',
            name='re_password_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
