# Generated by Django 3.1.5 on 2021-05-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0003_auto_20210520_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='remove_button',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='remove_button_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='remove_button_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
