# Generated by Django 3.1.5 on 2021-05-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0004_auto_20210520_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicelement',
            name='image_source',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='contains_elements',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='image_source',
        ),
        migrations.RemoveField(
            model_name='fertilizerdatasource',
            name='at_data_string',
        ),
        migrations.RemoveField(
            model_name='fertilizerdatasource',
            name='from_fertilizer',
        ),
        migrations.DeleteModel(
            name='FertilizerPageNames',
        ),
        migrations.DeleteModel(
            name='BasicElement',
        ),
        migrations.DeleteModel(
            name='ElementDataString',
        ),
        migrations.DeleteModel(
            name='Fertilizer',
        ),
        migrations.DeleteModel(
            name='FertilizerDataSource',
        ),
    ]
