# Generated by Django 3.1.5 on 2021-05-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0005_auto_20210520_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='wait_button',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='wait_button_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='wait_button_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
