# Generated by Django 3.1.5 on 2021-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0006_auto_20210531_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='second_third',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='second_third_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='second_third_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
