# Generated by Django 3.1.5 on 2021-06-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0007_auto_20210606_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover_en',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover_main',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover_main_en',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover_main_pl',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover_pl',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='allelopatic_conflict',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='allelopatic_conflict_en',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='allelopatic_conflict_pl',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='destroy_late_crop',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='destroy_late_crop_en',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='destroy_late_crop_pl',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='destroy_middle_crop',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='destroy_middle_crop_en',
        ),
        migrations.RemoveField(
            model_name='rotatoreditorpagenames',
            name='destroy_middle_crop_pl',
        ),
    ]
