# Generated by Django 3.1.5 on 2021-02-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0007_auto_20210208_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagenames',
            name='my_plans',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='my_plans_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='my_plans_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
