# Generated by Django 3.1.5 on 2021-02-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0008_auto_20210208_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='plan_limit_reached',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='plan_limit_reached_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='plan_limit_reached_pl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
