# Generated by Django 3.1.5 on 2021-02-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0011_auto_20210209_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagenames',
            name='lang_flag_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='lang_flag_id_en',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='lang_flag_id_pl',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
