# Generated by Django 3.1.5 on 2021-02-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0014_auto_20210210_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover_pl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
