# Generated by Django 3.1.5 on 2021-02-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0015_auto_20210211_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_main',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_main_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_main_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover_main',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover_main_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover_main_pl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover_en',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_onhover_pl',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='rotatoreditorpagenames',
            name='add_fertilizer_pl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
