# Generated by Django 3.1.5 on 2021-02-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0020_auto_20210211_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizerdatasource',
            name='descr_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fertilizerdatasource',
            name='descr_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fertilizerdatasource',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fertilizerdatasource',
            name='title_pl',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
