# Generated by Django 3.1.5 on 2021-02-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0021_auto_20210211_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdatastring',
            name='link_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='elementdatastring',
            name='link_pl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='elementdatastring',
            name='part1_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='elementdatastring',
            name='part1_pl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='elementdatastring',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='elementdatastring',
            name='title_pl',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
