# Generated by Django 3.1.5 on 2021-03-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0023_auto_20210211_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='middle_crop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='middle_crop_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='middle_crop_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
