# Generated by Django 3.1.5 on 2021-03-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0024_auto_20210303_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='destroy_middle_crop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='destroy_middle_crop_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='destroy_middle_crop_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
