# Generated by Django 3.1.5 on 2021-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0025_auto_20210303_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagenames',
            name='of_plants',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='of_plants_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='of_plants_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='of_steps',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='of_steps_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='of_steps_pl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
