# Generated by Django 3.1.5 on 2021-04-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0030_auto_20210330_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagenames',
            name='by_crops',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='by_crops_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='by_crops_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='by_families',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='by_families_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='by_families_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='by_tags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='by_tags_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagenames',
            name='by_tags_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
