# Generated by Django 3.1.5 on 2021-04-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0032_auto_20210402_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='categories',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='categories_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rotatoreditorpagenames',
            name='categories_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
