# Generated by Django 3.1.5 on 2021-04-03 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rotator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_pl', models.CharField(max_length=150, null=True)),
                ('title_en', models.CharField(max_length=150, null=True)),
                ('pubdate', models.DateTimeField(blank=True, null=True)),
                ('soil_type', models.PositiveSmallIntegerField(choices=[(0, 'Gleby Dobrej Jakości'), (1, 'Gleby Gorszej Jakości')], default=0)),
                ('published', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotation_plan_owner_set0', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pubdate'],
            },
        ),
        migrations.CreateModel(
            name='RotationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_pl', models.CharField(max_length=150, null=True)),
                ('title_en', models.CharField(max_length=150, null=True)),
                ('descr', models.CharField(blank=True, max_length=500, null=True)),
                ('descr_pl', models.CharField(blank=True, max_length=500, null=True)),
                ('descr_en', models.CharField(blank=True, max_length=500, null=True)),
                ('add_manure_early', models.BooleanField(default=False)),
                ('add_manure_middle', models.BooleanField(default=False)),
                ('add_manure_late', models.BooleanField(default=False)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('is_late_crop_destroy', models.BooleanField(default=False)),
                ('is_middle_crop_destroy', models.BooleanField(default=False)),
                ('is_early_crop_destroy', models.BooleanField(default=False)),
                ('early_crop', models.ManyToManyField(blank=True, related_name='crop_early_set0', to='rotator.Crop')),
                ('from_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotation_plan_set0', to='rekruter.rotationplan')),
                ('late_crop', models.ManyToManyField(blank=True, related_name='crop_late_set0', to='rotator.Crop')),
                ('middle_crop', models.ManyToManyField(blank=True, related_name='crop_middle_set0', to='rotator.Crop')),
            ],
            options={
                'verbose_name_plural': 'Rotation Steps',
                'ordering': ['-from_plan', 'order'],
            },
        ),
    ]
