# Generated by Django 3.1.5 on 2021-04-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0013_crop_is_crop_mix'),
        ('rekruter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationSubStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(choices=[(0, 'Plon Wczesny'), (1, 'Śródplon'), (2, 'Plon Późny')], default=0)),
                ('add_manure', models.BooleanField(default=False)),
                ('is_crop_destroy', models.BooleanField(default=False)),
                ('crop_substep', models.ManyToManyField(blank=True, related_name='crop_subtep_set', to='rotator.Crop')),
                ('from_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotation_step_set', to='rekruter.rotationstep')),
            ],
            options={
                'verbose_name_plural': 'Rotation Substeps',
                'ordering': ['-from_step', 'order'],
            },
        ),
    ]
