# Generated by Django 3.1.5 on 2021-04-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0002_rotationsubstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationsubstep',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Plon Wczesny'), (2, 'Śródplon'), (3, 'Plon Późny')], default=0),
        ),
    ]
