# Generated by Django 3.1.5 on 2021-05-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekruter', '0003_auto_20210427_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotationstep',
            name='add_manure_early',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='add_manure_late',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='add_manure_middle',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='early_crop',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='is_early_crop_destroy',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='is_late_crop_destroy',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='is_middle_crop_destroy',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='late_crop',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='middle_crop',
        ),
    ]
