# Generated by Django 3.1.3 on 2020-12-05 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('descr', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pubdate', models.DateTimeField(blank=True, null=True)),
                ('culture_override', models.PositiveSmallIntegerField(choices=[(0, 'Domyślnie dla Rodziny'), (1, 'Poprawia Jakość Gleby'), (2, 'Pogarsza Jakość Gleby'), (3, 'Neutralna Dla Jakości Gleby')], default=0)),
                ('cooldown_override', models.IntegerField(blank=True, null=True)),
                ('is_summercrop', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='CropFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latin_name', models.CharField(blank=True, max_length=150, null=True)),
                ('culture', models.PositiveSmallIntegerField(choices=[(1, 'Poprawia Jakość Gleby'), (2, 'Pogarsza Jakość Gleby'), (3, 'Neutralna Dla Jakości Gleby')], default=3)),
                ('cooldown', models.IntegerField(blank=True, null=True)),
                ('is_manurable', models.BooleanField(default=False)),
                ('culture_manured', models.PositiveSmallIntegerField(choices=[(1, 'Poprawia Jakość Gleby'), (2, 'Pogarsza Jakość Gleby'), (3, 'Neutralna Dla Jakości Gleby')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CropMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('descr', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pubdate', models.DateTimeField(blank=True, null=True)),
                ('ingredients', models.ManyToManyField(blank=True, to='rotator.Crop')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='RotationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('pubdate', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pubdate'],
            },
        ),
        migrations.CreateModel(
            name='RotationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('descr', models.CharField(blank=True, max_length=500, null=True)),
                ('add_manure', models.BooleanField(default=False)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('is_ac_main', models.BooleanField(default=False)),
                ('is_ac_harvest', models.BooleanField(default=False)),
                ('after_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rotator.crop')),
                ('after_crop_mix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rotator.cropmix')),
                ('co_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rotator.crop')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rotator.crop')),
                ('from_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rotator.rotationplan')),
            ],
            options={
                'ordering': ['-from_plan', 'order'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rotator.cropfamily'),
        ),
    ]
