# Generated by Django 3.1.5 on 2021-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropdatasource',
            options={'ordering': ['-from_crop', 'order', 'title']},
        ),
        migrations.AddField(
            model_name='cropdatasource',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
