# Generated by Django 3.1.3 on 2020-12-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='allelopatic_to',
            field=models.ManyToManyField(blank=True, to='rotator.Crop'),
        ),
    ]
