# Generated by Django 3.1.3 on 2020-12-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0002_crop_allelopatic_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropfamily',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Crop Families'},
        ),
        migrations.AlterModelOptions(
            name='cropmix',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Crop Mixes'},
        ),
        migrations.AlterModelOptions(
            name='rotationstep',
            options={'ordering': ['-from_plan', 'order'], 'verbose_name_plural': 'Rotation Steps'},
        ),
        migrations.AlterField(
            model_name='cropfamily',
            name='culture',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nie Dotyczy'), (1, 'Poprawia Jakość Gleby'), (2, 'Pogarsza Jakość Gleby'), (3, 'Neutralna Dla Jakości Gleby')], default=3),
        ),
        migrations.AlterField(
            model_name='cropfamily',
            name='culture_manured',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nie Dotyczy'), (1, 'Poprawia Jakość Gleby'), (2, 'Pogarsza Jakość Gleby'), (3, 'Neutralna Dla Jakości Gleby')], default=0),
        ),
        migrations.AlterField(
            model_name='rotationstep',
            name='after_crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_crop_set', to='rotator.crop'),
        ),
        migrations.AlterField(
            model_name='rotationstep',
            name='after_crop_mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_mix_set', to='rotator.cropmix'),
        ),
        migrations.AlterField(
            model_name='rotationstep',
            name='co_crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_crop_set', to='rotator.crop'),
        ),
        migrations.AlterField(
            model_name='rotationstep',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_main_set', to='rotator.crop'),
        ),
        migrations.AlterField(
            model_name='rotationstep',
            name='from_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotation_plan_set', to='rotator.rotationplan'),
        ),
    ]
