# Generated by Django 3.1.5 on 2021-04-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0002_auto_20210406_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropbookstring',
            options={'ordering': ['part1']},
        ),
    ]
