# Generated by Django 3.1.5 on 2021-04-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0002_auto_20210406_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropbookstring',
            options={'ordering': ['part1']},
        ),
        migrations.RenameField(
            model_name='cropfamily',
            old_name='family_relationships',
            new_name='crop_relationships',
        ),
    ]
