# Generated by Django 3.1.3 on 2020-12-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0003_auto_20201205_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='is_demanding',
            field=models.BooleanField(default=False),
        ),
    ]
