# Generated by Django 3.1.5 on 2021-04-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0003_auto_20210409_0841'),
        ('rotator', '0003_auto_20210409_0731'),
    ]

    operations = [
    ]
