# Generated by Django 3.1.5 on 2021-04-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0004_merge_20210409_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropinteraction',
            name='is_server_generated',
            field=models.BooleanField(default=False),
        ),
    ]
