# Generated by Django 3.1.3 on 2020-12-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0004_crop_is_demanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationplan',
            name='soil_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Gleby Dobrej Jakości'), (1, 'Gleby Gorszej Jakości')], default=0),
        ),
    ]
