# Generated by Django 3.1.3 on 2020-12-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0005_rotationplan_soil_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='cooldown_override',
            new_name='cooldown_max_override',
        ),
        migrations.RenameField(
            model_name='cropfamily',
            old_name='cooldown',
            new_name='cooldown_max',
        ),
        migrations.AddField(
            model_name='crop',
            name='cooldown_min_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropfamily',
            name='cooldown_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
