# Generated by Django 3.1.5 on 2021-04-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0005_cropinteraction_is_server_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropinteraction',
            name='server_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_server_set', to='rotator.croptag'),
        ),
    ]
