# Generated by Django 3.1.5 on 2021-04-20 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0006_cropinteraction_server_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropinteraction',
            name='server_tag',
        ),
        migrations.AddField(
            model_name='cropinteraction',
            name='server_interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_interaction_set', to='rotator.cropinteraction'),
        ),
    ]
