# Generated by Django 3.1.3 on 2020-12-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0007_auto_20201205_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['family', 'name']},
        ),
        migrations.AlterModelOptions(
            name='cropfamily',
            options={'ordering': ['name'], 'verbose_name_plural': 'Crop Families'},
        ),
        migrations.AlterModelOptions(
            name='cropmix',
            options={'ordering': ['name'], 'verbose_name_plural': 'Crop Mixes'},
        ),
    ]
