# Generated by Django 3.1.5 on 2021-04-20 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0008_cropinteraction_debug_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropinteraction',
            name='trigger_crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_crop_set', to='rotator.crop'),
        ),
    ]
