# Generated by Django 3.1.5 on 2021-04-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0009_cropinteraction_trigger_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropinteraction',
            name='trigger_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_tag_set', to='rotator.croptag'),
        ),
    ]
