# Generated by Django 3.1.5 on 2021-04-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0010_cropinteraction_trigger_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixCrop',
            fields=[
                ('crop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rotator.crop')),
                ('meta_tags', models.TextField()),
            ],
            bases=('rotator.crop',),
        ),
    ]
