# Generated by Django 3.1.3 on 2020-12-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0010_auto_20201208_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='synergic_to',
            field=models.ManyToManyField(blank=True, related_name='known_synergies', to='rotator.Crop'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='allelopatic_to',
            field=models.ManyToManyField(blank=True, related_name='known_antagonisms', to='rotator.Crop'),
        ),
    ]
