# Generated by Django 3.1.3 on 2020-12-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0011_auto_20201208_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('descr', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='special_tags', to='rotator.Crop'),
        ),
    ]
