# Generated by Django 3.1.5 on 2021-04-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0011_mixcrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='meta_tags_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mixcrop',
            name='meta_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
