# Generated by Django 3.1.3 on 2020-12-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0012_auto_20201208_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='special_tags', to='rotator.CropTag'),
        ),
    ]
