# Generated by Django 3.1.5 on 2021-04-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0013_crop_is_crop_mix'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='is_fertilizer',
            field=models.BooleanField(default=False),
        ),
    ]
