# Generated by Django 3.1.5 on 2021-04-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0014_crop_is_fertilizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixcrop',
            name='redirect_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mixcrop',
            name='redirect_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
