# Generated by Django 3.1.3 on 2020-12-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0014_remove_crop_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='special_tags', to='rotator.CropTag'),
        ),
    ]
