# Generated by Django 3.1.5 on 2021-04-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0015_auto_20210429_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mixcrop',
            name='redirect_id',
        ),
        migrations.RemoveField(
            model_name='mixcrop',
            name='redirect_name',
        ),
        migrations.AddField(
            model_name='crop',
            name='redirect_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='redirect_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
