# Generated by Django 3.1.3 on 2020-12-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0015_crop_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='allelopatic_to_family',
            field=models.ManyToManyField(blank=True, related_name='known_antagonisms_family', to='rotator.CropFamily'),
        ),
        migrations.AddField(
            model_name='crop',
            name='allelopatic_to_tag',
            field=models.ManyToManyField(blank=True, related_name='known_antagonisms_tag', to='rotator.CropTag'),
        ),
        migrations.AddField(
            model_name='crop',
            name='synergic_to_family',
            field=models.ManyToManyField(blank=True, related_name='known_synergies_family', to='rotator.CropFamily'),
        ),
        migrations.AddField(
            model_name='crop',
            name='synergic_to_tag',
            field=models.ManyToManyField(blank=True, related_name='known_synergies_tag', to='rotator.CropTag'),
        ),
    ]
