# Generated by Django 3.1.3 on 2020-12-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0016_auto_20201208_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='seed_norm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
