# Generated by Django 3.1.3 on 2020-12-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0018_auto_20201209_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rotationstep',
            old_name='is_ac_harvest',
            new_name='is_harvest',
        ),
        migrations.RenameField(
            model_name='rotationstep',
            old_name='is_ac_main',
            new_name='is_late_crop_destroy',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='after_crop',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='after_crop_mix',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='co_crop',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='crop',
        ),
        migrations.AddField(
            model_name='rotationstep',
            name='early_crop',
            field=models.ManyToManyField(blank=True, related_name='crop_early_set', to='rotator.Crop'),
        ),
        migrations.AddField(
            model_name='rotationstep',
            name='late_crop',
            field=models.ManyToManyField(blank=True, related_name='crop_late_set', to='rotator.Crop'),
        ),
    ]
