# Generated by Django 3.1.5 on 2021-05-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0018_auto_20210430_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropinteraction',
            name='interaction_sign',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Brak'), (1, 'Szkodzi'), (2, 'Wspiera')], default=0),
        ),
    ]
