# Generated by Django 3.1.3 on 2020-12-31 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0020_auto_20201219_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rotationstep',
            old_name='is_harvest',
            new_name='is_early_crop_destroy',
        ),
    ]
