# Generated by Django 3.1.3 on 2021-01-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0021_auto_20201231_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropDataString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('part1', models.CharField(blank=True, max_length=500, null=True)),
                ('part2', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('descr', models.CharField(blank=True, max_length=500, null=True)),
                ('at_data_string', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_data_string_set', to='rotator.cropdatastring')),
                ('at_tag', models.ManyToManyField(blank=True, related_name='crop_source_tag_set', to='rotator.CropTag')),
                ('from_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_source_set', to='rotator.crop')),
            ],
        ),
    ]
