# Generated by Django 3.1.5 on 2021-05-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0021_auto_20210506_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropinteraction',
            options={'ordering': ['is_server_generated', 'title']},
        ),
    ]
