# Generated by Django 3.1.5 on 2021-05-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0022_auto_20210506_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropsinteraction',
            options={'ordering': ['is_server_generated', 'title']},
        ),
        migrations.AlterModelOptions(
            name='familyinteraction',
            options={'ordering': ['is_server_generated', 'title']},
        ),
        migrations.AlterModelOptions(
            name='tagsinteraction',
            options={'ordering': ['is_server_generated', 'title']},
        ),
    ]
