# Generated by Django 3.1.3 on 2021-01-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0023_auto_20210102_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropdatasource',
            options={'ordering': ['-from_crop', 'title']},
        ),
        migrations.AlterModelOptions(
            name='cropdatastring',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='cropdatasource',
            old_name='from_plan',
            new_name='from_crop',
        ),
    ]
