# Generated by Django 3.1.5 on 2021-05-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0023_auto_20210507_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropinteraction',
            name='debug_line',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
