# Generated by Django 3.1.5 on 2021-05-31 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0024_auto_20210520_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropinteraction',
            name='is_positive',
        ),
    ]
