# Generated by Django 3.1.3 on 2021-01-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0024_auto_20210102_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropdatasource',
            name='descr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
