# Generated by Django 3.1.3 on 2021-01-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0025_auto_20210102_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropdatastring',
            old_name='part2',
            new_name='link',
        ),
    ]
