# Generated by Django 3.1.5 on 2021-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0025_remove_cropinteraction_is_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropinteraction',
            name='type_of_interaction',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Współrzędne'), (1, 'Allelopatyczne'), (2, 'Następcze'), (3, 'W drugim roku'), (4, 'W trzecim roku'), (5, 'W dwóch kolejnych latach'), (6, 'W kolejnym roku'), (7, 'W drugim i drzecim roku')], default=0),
        ),
    ]
