# Generated by Django 3.1.5 on 2021-06-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0026_auto_20210606_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='is_deep_roots',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='is_demanding',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='is_leaves_mess',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='plant_type',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='redirect_id',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='redirect_name',
        ),
        migrations.RemoveField(
            model_name='cropfamily',
            name='culture_manured',
        ),
        migrations.RemoveField(
            model_name='cropfamily',
            name='is_manurable',
        ),
    ]
