# Generated by Django 3.1.3 on 2021-01-03 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0027_auto_20210102_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('is_positive', models.BooleanField(default=True)),
                ('start_int', models.IntegerField(default=0)),
                ('end_int', models.IntegerField(default=0)),
                ('about_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_interaction_set', to='rotator.crop')),
                ('about_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_interaction_set', to='rotator.cropfamily')),
            ],
        ),
        migrations.AlterField(
            model_name='cropdatasource',
            name='from_crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_source_set', to='rotator.crop'),
        ),
        migrations.CreateModel(
            name='FamilyInteraction',
            fields=[
                ('cropinteraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rotator.cropinteraction')),
            ],
            bases=('rotator.cropinteraction',),
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_relationships',
            field=models.ManyToManyField(blank=True, related_name='known_crop_interactions', to='rotator.CropInteraction'),
        ),
        migrations.AddField(
            model_name='cropdatasource',
            name='from_interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_source_set', to='rotator.cropinteraction'),
        ),
    ]
