# Generated by Django 3.1.3 on 2021-01-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0031_auto_20210103_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='allelopatic_to',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='allelopatic_to_family',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='bad_before',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='good_before',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='is_summercrop',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='synergic_to',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='synergic_to_family',
        ),
    ]
