# Generated by Django 3.1.5 on 2021-01-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0033_cropfamily_family_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropfamily',
            name='family_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_subtype_set', to='rotator.cropfamily'),
        ),
        migrations.AddField(
            model_name='cropfamily',
            name='is_family_subtype',
            field=models.BooleanField(default=False),
        ),
    ]
