# Generated by Django 3.1.5 on 2021-01-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0034_auto_20210108_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropfamily',
            name='family_slaves',
            field=models.ManyToManyField(blank=True, related_name='family_slaves_set', to='rotator.CropFamily'),
        ),
    ]
