# Generated by Django 3.1.5 on 2021-01-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0035_cropfamily_family_slaves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropfamily',
            old_name='is_family_subtype',
            new_name='is_family_slave',
        ),
    ]
