# Generated by Django 3.1.5 on 2021-01-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0037_auto_20210108_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['name']},
        ),
    ]
