# Generated by Django 3.1.5 on 2021-01-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0038_auto_20210108_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationplan',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
