# Generated by Django 3.1.5 on 2021-02-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0039_rotationplan_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rotationstep',
            old_name='add_manure',
            new_name='add_manure_early',
        ),
        migrations.AddField(
            model_name='rotationstep',
            name='add_manure_late',
            field=models.BooleanField(default=False),
        ),
    ]
