# Generated by Django 3.1.5 on 2021-02-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0040_auto_20210201_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropinteraction',
            name='type_of_interaction',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Współrzędne'), (1, 'Allelopatyczne'), (2, 'Następcze')], default=0),
        ),
    ]
