# Generated by Django 3.1.5 on 2021-02-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0041_cropinteraction_type_of_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropinteraction',
            name='end_int',
        ),
        migrations.RemoveField(
            model_name='cropinteraction',
            name='start_int',
        ),
    ]
