# Generated by Django 3.1.5 on 2021-02-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0045_auto_20210209_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptag',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='croptag',
            name='name_pl',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
