# Generated by Django 3.1.5 on 2021-02-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0046_auto_20210209_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropImagesSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('at_data_string', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_data_string_set1', to='rotator.cropdatastring')),
                ('from_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_source_set1', to='rotator.crop')),
            ],
            options={
                'ordering': ['-from_crop', 'title'],
            },
        ),
    ]
