# Generated by Django 3.1.5 on 2021-02-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0050_auto_20210216_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropinteraction',
            name='season_of_interaction',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nie Dotyczy'), (1, 'Jare'), (2, 'Ozime')], default=0),
        ),
    ]
