# Generated by Django 3.1.5 on 2021-02-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0051_cropinteraction_season_of_interaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropBookString',
            fields=[
                ('cropdatastring_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rotator.cropdatastring')),
            ],
            options={
                'ordering': ['title'],
            },
            bases=('rotator.cropdatastring',),
        ),
        migrations.CreateModel(
            name='CropImageString',
            fields=[
                ('cropdatastring_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rotator.cropdatastring')),
            ],
            options={
                'ordering': ['title'],
            },
            bases=('rotator.cropdatastring',),
        ),
    ]
