# Generated by Django 3.1.5 on 2021-02-19 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0052_cropbookstring_cropimagestring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_image_cds', to='rotator.cropimagestring'),
        ),
        migrations.AlterField(
            model_name='cropdatasource',
            name='at_data_string',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_data_string_set', to='rotator.cropbookstring'),
        ),
    ]
