# Generated by Django 3.1.5 on 2021-03-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0053_auto_20210219_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationstep',
            name='add_manure_middle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rotationstep',
            name='is_middle_crop_destroy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rotationstep',
            name='middle_crop',
            field=models.ManyToManyField(blank=True, related_name='crop_middle_set', to='rotator.Crop'),
        ),
    ]
