# Generated by Django 3.1.5 on 2021-03-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0054_auto_20210303_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptag',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
