# Generated by Django 3.1.5 on 2021-03-26 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0055_croptag_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropFamilySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('descr', models.TextField(blank=True, null=True)),
                ('descr_pl', models.TextField(blank=True, null=True)),
                ('descr_en', models.TextField(blank=True, null=True)),
                ('pages_from', models.IntegerField(blank=True, null=True)),
                ('pages_to', models.IntegerField(blank=True, null=True)),
                ('at_data_string', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_family_string_set', to='rotator.cropbookstring')),
                ('from_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_family_source_set', to='rotator.cropfamily')),
            ],
            options={
                'ordering': ['-from_family', 'title'],
            },
        ),
    ]
