# Generated by Django 3.1.5 on 2021-03-26 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0056_cropfamilysource'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropDataFamilySource',
            fields=[
                ('cropdatasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rotator.cropdatasource')),
                ('from_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_data_family_source_set', to='rotator.cropfamily')),
            ],
            bases=('rotator.cropdatasource',),
        ),
    ]
