# Generated by Django 3.1.5 on 2021-03-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0057_cropdatafamilysource'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdatafamilysource',
            name='descr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropdatafamilysource',
            name='descr2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropdatafamilysource',
            name='descr2_pl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
