# Generated by Django 3.1.5 on 2021-03-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0058_auto_20210326_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropdatafamilysource',
            name='descr2',
        ),
        migrations.RemoveField(
            model_name='cropdatafamilysource',
            name='descr2_en',
        ),
        migrations.RemoveField(
            model_name='cropdatafamilysource',
            name='descr2_pl',
        ),
    ]
