# Generated by Django 3.1.5 on 2021-03-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0059_auto_20210326_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropFamilySource',
        ),
    ]
