# Generated by Django 3.1.5 on 2021-03-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0060_delete_cropfamilysource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotationstep',
            name='early_crop',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='from_plan',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='late_crop',
        ),
        migrations.RemoveField(
            model_name='rotationstep',
            name='middle_crop',
        ),
        migrations.DeleteModel(
            name='RotationPlan',
        ),
        migrations.DeleteModel(
            name='RotationStep',
        ),
    ]
