# Generated by Django 3.1.5 on 2021-03-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotator', '0062_cropdatatagsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='plant_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Roczna'), (1, 'Dwuletnia'), (2, 'Wieloletnia')], default=0),
        ),
    ]
